name: Keep Render App Alive

on:
  schedule:
    # Runs every 12 minutes, every day
    - cron: '*/12 * * * *'
  workflow_dispatch: # Allows you to run this manually from the GitHub website

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: |
          curl -I https://beru-bot-t7c6.onrender.com